
openapi: 3.0.3
info:
  title: JusticeLink Court Search
  version: "1.0"
servers:
  - url: https://justicelink.onrender.com
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200": { description: OK }
  /cases/search:
    get:
      summary: Search court cases
      parameters:
        - name: q
          in: query
          required: true
          schema: { type: string }
        - name: limit
          in: query
          required: false
          schema: { type: integer, minimum: 1, maximum: 50, default: 20 }
        - name: offset
          in: query
          required: false
          schema: { type: integer, minimum: 0, default: 0 }
      responses:
        "200": { description: OK }
        "400": { description: Bad Request }
        "401": { description: Unauthorized }
        "500": { description: Server Error }
